export const STEPS = {
  PROFILE_SETUP: 'PROFILE_SETUP',
  INTERVIEWER_SELECTION: 'INTERVIEWER_SELECTION',
  TRANSITIONING_TO_OFFICE: 'TRANSITIONING_TO_OFFICE',
  IN_OFFICE: 'IN_OFFICE'
};

export const AVATAR_STATES = {
  IDLE: 'IDLE',
  THINKING: 'THINKING',
  SPEAKING: 'SPEAKING',
  LISTENING: 'LISTENING'
};
