export const STEPS = {
  PROFILE_SETUP: 'PROFILE_SETUP',
  ORGANIZATION_SELECTION: 'ORGANIZATION_SELECTION',
  INTERVIEWER_SELECTION: 'INTERVIEWER_SELECTION',
  WAITING_ROOM: 'WAITING_ROOM',
  TRANSITIONING_TO_OFFICE: 'TRANSITIONING_TO_OFFICE',
  IN_OFFICE: 'IN_OFFICE',
  REPORT_VIEW: 'REPORT_VIEW'
};

export const AVATAR_STATES = {
  IDLE: 'IDLE',
  THINKING: 'THINKING',
  SPEAKING: 'SPEAKING',
  LISTENING: 'LISTENING'
};

/**
 * Authoritative Interview Lifecycle States.
 * Strictly prevents conflicting or overlapping states.
 */
export const INTERVIEW_STATES = {
  IDLE: 'IDLE',
  CAMERA_INITIALIZING: 'CAMERA_INITIALIZING',
  READY: 'READY',
  INTERVIEWER_SPEAKING: 'INTERVIEWER_SPEAKING',
  WAITING_FOR_CANDIDATE: 'WAITING_FOR_CANDIDATE',
  CANDIDATE_SPEAKING: 'CANDIDATE_SPEAKING',
  TRANSCRIBING: 'TRANSCRIBING',
  ANALYZING: 'ANALYZING',
  NEXT_QUESTION: 'NEXT_QUESTION'
};
